services:
  web:
    build: .
    container_name: pwa_chat
    restart: always
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    # Si vous avez un fichier .env pour les variables d'environnement
    # env_file:
    #   - .env
